"""
report.py — PDF Threat Report Generator
-----------------------------------------
Generates a professional PDF threat investigation report
containing executive summary, severity charts, detailed alerts,
recommendations, and investigation conversation log.

Usage:
    from report import generate_report
    path = generate_report(alerts, chat_history)
"""

from fpdf import FPDF
from datetime import datetime
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import os


class ThreatReport(FPDF):

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_fill_color(20, 40, 80)
        self.set_text_color(255, 255, 255)
        self.cell(0, 15, "  Conversational SIEM - Threat Investigation Report",
                  new_x="LMARGIN", new_y="NEXT", fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10,
                  f"Generated by Conversational SIEM Assistant | Page {self.page_no()} | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                  align="C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 13)
        self.set_fill_color(220, 230, 245)
        self.set_text_color(20, 40, 80)
        self.cell(0, 10, f"  {title}", new_x="LMARGIN", new_y="NEXT", fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def body_text(self, text):
        self.set_font("Helvetica", "", 11)
        self.set_text_color(50, 50, 50)
        text = text.encode("latin-1", "replace").decode("latin-1")
        self.multi_cell(0, 8, text)
        self.ln(2)

    def alert_box(self, alert, index):
        level = 0
        try:
            level = int(alert.get("rule", {}).get("level", 0) or 0)
        except:
            pass

        if level >= 10:
            self.set_fill_color(255, 200, 200)
            severity = "[HIGH]"
        elif level >= 5:
            self.set_fill_color(255, 235, 180)
            severity = "[MEDIUM]"
        else:
            self.set_fill_color(200, 240, 210)
            severity = "[LOW]"

        self.set_font("Helvetica", "B", 11)
        self.set_text_color(30, 30, 30)
        self.cell(0, 9, f"  Alert {index} - {severity} (Level {level})",
                  new_x="LMARGIN", new_y="NEXT", fill=True)

        self.set_font("Helvetica", "", 10)
        self.set_fill_color(248, 248, 248)

        desc  = alert.get('rule', {}).get('description', 'N/A').encode("latin-1", "replace").decode("latin-1")
        agent = alert.get('agent', {}).get('name', 'N/A').encode("latin-1", "replace").decode("latin-1")

        self.cell(0, 7, f"  Description : {desc}",  new_x="LMARGIN", new_y="NEXT", fill=True)
        self.cell(0, 7, f"  Agent/Machine: {agent}", new_x="LMARGIN", new_y="NEXT", fill=True)
        self.cell(0, 7, f"  Timestamp    : {alert.get('timestamp', 'N/A')}", new_x="LMARGIN", new_y="NEXT", fill=True)
        self.cell(0, 7, f"  Rule ID      : {alert.get('rule', {}).get('id', 'N/A')}", new_x="LMARGIN", new_y="NEXT", fill=True)
        self.ln(4)


def generate_pie_chart(high, medium, low):
    """Generate severity distribution pie chart"""
    labels, sizes, colors = [], [], []
    if high   > 0: labels.append(f"High ({high})");     sizes.append(high);   colors.append("#FF4B4B")
    if medium > 0: labels.append(f"Medium ({medium})"); sizes.append(medium); colors.append("#FFA500")
    if low    > 0: labels.append(f"Low ({low})");       sizes.append(low);    colors.append("#00AA33")

    if not sizes:
        return None

    fig, ax = plt.subplots(figsize=(5, 4), facecolor="white")
    wedges, texts, autotexts = ax.pie(
        sizes, labels=labels, colors=colors,
        autopct="%1.1f%%", startangle=140,
        wedgeprops={"edgecolor": "white", "linewidth": 2}
    )
    for t in texts:      t.set_fontsize(11)
    for at in autotexts: at.set_fontsize(10); at.set_color("white"); at.set_fontweight("bold")

    ax.set_title("Alert Severity Distribution", fontsize=13, fontweight="bold", pad=15)
    plt.tight_layout()

    path = "/home/kali/conversational-siem/siem_pie_chart.png"
    plt.savefig(path, dpi=150, bbox_inches="tight", facecolor="white")
    plt.close()
    return path


def get_recommendations(alerts):
    """Generate recommendations based on detected alert types"""
    descriptions = [a.get("rule", {}).get("description", "").lower() for a in alerts]
    recs = []

    if any("login" in d or "authentication" in d or "failed" in d for d in descriptions):
        recs.append("AUTHENTICATION ALERTS: Review all failed login attempts. Implement account lockout after 3-5 failed attempts. Enable multi-factor authentication (MFA) for critical accounts.")

    if any("sudo" in d or "root" in d or "privilege" in d for d in descriptions):
        recs.append("PRIVILEGE ESCALATION: Monitor all sudo/root access. Enforce least privilege principle. Review sudoers file for unauthorized entries.")

    if any("scan" in d or "recon" in d or "port" in d for d in descriptions):
        recs.append("RECONNAISSANCE DETECTED: A port scan was detected. Identify and block the source IP at the firewall. Review network segmentation policies.")

    if any("user" in d or "account" in d or "adduser" in d for d in descriptions):
        recs.append("USER ACCOUNT CHANGES: New accounts or modifications detected. Verify these changes were authorized. Review user management policies.")

    if any("file" in d or "integrity" in d for d in descriptions):
        recs.append("FILE INTEGRITY ALERT: Unauthorized file modifications detected. Verify changes and run a malware scan on affected systems.")

    if any("pam" in d or "session" in d for d in descriptions):
        recs.append("SESSION ACTIVITY: Multiple login sessions recorded. Review and terminate any unauthorized active sessions.")

    if not recs:
        recs.append("No specific threat patterns detected. Continue monitoring and ensure all agents are properly configured.")

    return recs


def generate_report(alerts, chat_history, output_path="/home/kali/conversational-siem/siem_report.pdf"):
    """Generate complete PDF threat investigation report"""
    pdf = ThreatReport()
    pdf.add_page()

    now    = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    high   = sum(1 for a in alerts if int(a.get("rule", {}).get("level", 0) or 0) >= 10)
    medium = sum(1 for a in alerts if 5 <= int(a.get("rule", {}).get("level", 0) or 0) < 10)
    low    = sum(1 for a in alerts if int(a.get("rule", {}).get("level", 0) or 0) < 5)

    if high > 0:
        risk = "HIGH RISK - Immediate action required"
    elif medium > 0:
        risk = "MEDIUM RISK - Investigation recommended"
    else:
        risk = "LOW RISK - Continue monitoring"

    # ── 1. Executive Summary ──────────────────
    pdf.section_title("1. Executive Summary")
    pdf.body_text(
        f"Report Date        : {now}\n"
        f"Overall Risk Level : {risk}\n"
        f"Total Alerts       : {len(alerts)}\n"
        f"High Severity      : {high}\n"
        f"Medium Severity    : {medium}\n"
        f"Low Severity       : {low}\n"
        f"SIEM Platform      : Wazuh\n"
        f"Investigation Tool : Conversational SIEM Assistant (NLP + AI)\n\n"
        f"This report summarizes the security events detected by the Wazuh SIEM system. "
        f"The AI assistant analyzed {len(alerts)} alerts across all monitored agents and "
        f"identified the key threats described in the sections below."
    )

    # ── 2. Severity Chart ─────────────────────
    pdf.section_title("2. Severity Distribution Chart")
    chart_path = generate_pie_chart(high, medium, low)
    if chart_path and os.path.exists(chart_path):
        pdf.image(chart_path, x=55, w=100)
        pdf.ln(5)
    else:
        pdf.body_text("No chart available (no alerts detected).")

    # ── 3. Alert Summary ──────────────────────
    pdf.section_title("3. Alert Summary")
    pdf.body_text(
        f"High Severity  (Level 10+) : {high} alert(s) - Require immediate attention\n"
        f"Medium Severity (Level 5-9): {medium} alert(s) - Require investigation\n"
        f"Low Severity   (Level 0-4) : {low} alert(s) - For monitoring purposes"
    )

    # ── 4. Detailed Alerts ────────────────────
    pdf.add_page()
    pdf.section_title("4. Detailed Alert Log")
    if alerts:
        for i, alert in enumerate(alerts, 1):
            pdf.alert_box(alert, i)
            if pdf.get_y() > 250:
                pdf.add_page()
    else:
        pdf.body_text("No alerts were recorded during this investigation session.")

    # ── 5. Recommendations ────────────────────
    pdf.add_page()
    pdf.section_title("5. Recommendations Based on Detected Threats")
    for i, rec in enumerate(get_recommendations(alerts), 1):
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(20, 40, 80)
        pdf.cell(0, 8, f"Recommendation {i}:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        pdf.multi_cell(0, 7, f"  {rec.encode('latin-1', 'replace').decode('latin-1')}")
        pdf.ln(3)

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(20, 40, 80)
    pdf.cell(0, 8, "General Security Recommendations:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 7,
        "  - Keep all systems patched and up to date.\n"
        "  - Conduct regular vulnerability assessments.\n"
        "  - Review and update firewall rules periodically.\n"
        "  - Maintain and test incident response procedures.\n"
        "  - Train staff on security awareness and phishing prevention."
    )

    # ── 6. Chat History ───────────────────────
    if chat_history:
        pdf.add_page()
        pdf.section_title("6. Investigation Conversation Log")
        for msg in chat_history:
            role = "Analyst" if msg["role"] == "user" else "AI Assistant"
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(20, 40, 80)
            pdf.cell(0, 8, f"{role}:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(60, 60, 60)
            content = msg["content"].encode("latin-1", "replace").decode("latin-1")
            pdf.multi_cell(0, 7, content)
            pdf.ln(3)
            if pdf.get_y() > 260:
                pdf.add_page()

    pdf.output(output_path)
    return output_path


# ── Test ──────────────────────────────────────
if __name__ == "__main__":
    test_alerts = [
        {"rule": {"description": "Multiple failed login attempts", "level": "10", "id": "100002"},
         "agent": {"name": "WIN10"}, "timestamp": "2026-02-23 13:21:00"},
        {"rule": {"description": "New user account created", "level": "8", "id": "100003"},
         "agent": {"name": "WIN10"}, "timestamp": "2026-02-23 13:22:00"},
        {"rule": {"description": "Successful sudo to ROOT executed", "level": "3", "id": "5402"},
         "agent": {"name": "kali"}, "timestamp": "2026-02-23 13:23:00"},
    ]
    test_chat = [
        {"role": "user",      "content": "Are there any critical threats?"},
        {"role": "assistant", "content": "Yes, high severity alerts detected on WIN10."},
    ]
    path = generate_report(test_alerts, test_chat)
    print(f"Report generated at: {path}")
